"""initial_orm_baseline

Empty baseline. The schema (tables, indexes, RLS, triggers) was already
created by the Supabase migrations in supabase/migrations/. This revision
exists only as the Alembic starting point so future autogenerated
migrations have something to chain to.

Revision ID: e97587feff9b
Revises:
Create Date: 2026-05-27 00:33:27.107135

"""
from typing import Sequence, Union


revision: str = "e97587feff9b"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass


def downgrade() -> None:
    pass
